PORT 					= '/dev/tty.usbmodem1'	# whic port the pixhawk is on
BURN_PIN 				= 27				# pin with burn relay
BURN_ALTITUDE 			= 10 			    # altitude at which to burn
BURN_TIME_ABOVE 		= 10				# time above burn alt before ignite
BURN_TIME_BELOW			= 3					# time below burn alt after ignite
TARGET_LAT	 			= 42.345131			# desired landing latitude
TARGET_LON				= -71.210126		# desired landing longitude
TARGET_ALT 				= 0 				# meters above sea level
LOOP_DELAY				= 0.5				# time in seconds to delay within loops
